### ISSUE TITLE
Replit Issue

### ISSUE THREAD

**Issue by 0deep0** [Ib69/epic-games-phishing#3]
it doesn't send the hits to discord even tho I put the webhook url

**Comment by 0deep0** [comment]
Don't I need a bot?

**Comment by Ib69** [comment]
No you only need a webhook.
If its not working i will fix the problems.

**Comment by 0deep0** [comment]
it's not working unfortunately

**Comment by Ib69** [comment]
i just tested, all is working fine
what host are you using to your website ?

**Comment by carlitobones** [comment]
doesn't send anything to my discord server even though I got my web hook url in there

**Comment by Ib69** [comment]
witch host are you using ?

**Comment by carlitobones** [comment]
replit, the only thing I did was copy my discord's weburl in

**Comment by ItzJair** [comment]
I can’t get it to work either

**Comment by Ib69** [comment]
you will need to download the code then upload it manually on replit and not use the "Import From Github" button.

and you will have to select the "Php Web Server" option

**Comment by Ib69** [comment]
![steps_to_create](https://user-images.githubusercontent.com/79330711/224480390-a24e6869-fb8b-4b29-93c8-b6f8c87f2f3e.png)

I made this so you can understand how to create it xD
