### ISSUE TITLE
Webhook

### ISSUE THREAD

**Issue by ItzJair** [Ib69/epic-games-phishing#4]
When ever I enter in details it just loads a white page with all the code and doesn’t send to my webhook

**Comment by Ib69** [comment]
send me a screen shot

**Comment by Ib69** [comment]
If you have any problem with replit i invite you to check https://github.com/Ib69/epic-games-phishing/issues/3

**Comment by ItzJair** [comment]
I added you on discord can we discuss the issue on discord

**Comment by Ib69** [comment]
add me on my new discord ib!#1804
